spring.application.name=order-and-notification-service
spring.profiles.default=local
server.port=${PORT:8084}
spring.config.import=optional:file:.env[.properties],optional:file:../bidmart-infrastructure/.env[.properties]

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:orders;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,info
